kind: pipeline
type: docker
name: Push Image

trigger:
  event:
    exclude:
      - pull_request

steps:
  # Build
  - name: docker-image-test
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: docker-user
      password:
        from_secret: docker-key
      repo: randomman552/drone-build-reporter
      tags:
        - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        exclude:
          - main
          - master
          
  # Test build started message
  - name: test-build-started
    image: randomman552/drone-build-reporter:${DRONE_COMMIT_BRANCH}
    pull: always
    settings:
      gotify_token:
        from_secret: gotify-token
      gotify_url:
        from_secret: gotify-url
      discord_webhook:
        from_secret: discord-webhook
      notify_mode: started
    when:
      status:
        - failure
        - success
      branch:
        exclude:
          - main
          - master

  # Build latest
  - name: docker-image-latest
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: docker-user
      password:
        from_secret: docker-key
      repo: randomman552/drone-build-reporter
      tags:
        - latest
        - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - main
        - master

  # Report finished
  - name: report-finished
    image: randomman552/drone-build-reporter:${DRONE_COMMIT_BRANCH}
    pull: always
    settings:
      gotify_token:
        from_secret: gotify-token
      gotify_url:
        from_secret: gotify-url
      discord_webhook:
        from_secret: discord-webhook
    when:
      status:
        - failure
        - success
